version: '3'

services:
  liferay:
    image: liferay/dxp:202x.qx.x

    environment:      
      LIFERAY_JPDA_ENABLED: "true" 
      #JPDA_ADDRESS: 0.0.0.0:8000
      LIFERAY_DISABLE_TRIAL_LICENSE: "true"
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND: "true"

      GLOWROOT_ENABLED: "true"

      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: org.postgresql.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:postgresql://${MACHINE_HOST_IP}:5432/202x.qx.x
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: liferay
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: xz0ZHD5UeE

      # LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      # LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://${MACHINE_HOST_IP}:3306/70-fp102
      # LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: root
      # LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: root

      #LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: oracle.jdbc.OracleDriver
      #LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:oracle:thin:@${MACHINE_HOST_IP}:1521:ORCLCDB
      #LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: LPORTAL
      #LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: lportal
      
      #LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN: "true"

    ports:
      - 8000:8000
      - 8080:8080
      - 11311:11311 
      - 9201:9201 # Elassticsearch, 7.0-7.2 -> 9200, 7.3+ -> 9201

    volumes:
      - ./liferay:/mnt/liferay
      - ./scripts:/usr/local/liferay/scripts
      - ./data:/opt/liferay/data
      - ./logs:/opt/liferay/logs

  # mail:
  #   image: munkyboy/fakesmtp:latest
  #   privileged: true
  #   container_name: mail
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 1G
  #   hostname: mail
  #   ports:
  #     - "25:25"
  #   volumes: 
  #     - ./fakesmtp:/var/mail
  # mail-web:
  #   image: mjstewart/fakesmtp-web:1.3
  #   container_name: mail-web
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #       reservations:
  #         memory: 1G
  #   ports: 
  #     - "60500:8080"
  #   volumes:
  #     - ./fakesmtp:/var/mail
  #   environment:
  #     - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=30
  #   depends_on:
  #     - mail

#networks:
#  lr-network:
#    driver: bridge

    